[project]
name = "mcq-generator"
version = "0.1.0"
description = "Multiple Choice Questions generator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google>=3.0.0",
    "openai",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "reportlab>=4.4.5",
]
